### ISSUE TITLE
Probleme beim Laden der Klassen

### ISSUE THREAD

**Issue by Nobs77** [EffnerAppArchive/effnerapp-android-legacy#111]
Hi,

erstmal vorweg - Super Idee und tolle Umsetzung Eure App! 

Ich hab die App kürzlich auf dem S6Edge meines Sohnes eingerichtet. Installation läuft einwandfrei aber bei der Anmeldemaske kommt die Meldung "Fehler beim Laden der Klassen" - auf meinem S20 FE und auf dem S8 meiner Tochter funktioniert alles soweit. 

**Infos zum Handy:**
Samsung S6Edge
Android 7

Das ist natürlich schon etwas älter, aber gerade als erstes Handy für einen 5. Klässler absolut ausreichend. Wenn Ihr Android 7 nicht mehr unterstützt, würd ich das natürlich verstehen. ;-)

Viele Grüße und weiter so!

**Comment by clyaIO** [comment]
Vielen Dank für ihre Meldung, es scheint ein generelles Problem mit Android 7 zu geben, wir werden uns darum kümmern!

**Comment by Nobs77** [comment]
Super! Danke schonmal!

**Comment by Luuuuuis** [comment]
Hi,

vielen Dank für das Feedback!

Wir haben herausgefunden, dass das Problem an Android 7.0 liegt und schon in Android 7.1.1 gefixt wurde.
Trotzdem konnten wir den Fehler lösen. Das Update wird zeitnah im Play Store sein.

**Comment by Nobs77** [comment]
Ihr seid ja fix! Werde testen und berichten.

**Comment by Luuuuuis** [comment]
Update ist nun. Live im Play Store!

**Comment by Nobs77** [comment]
Funktioniert nun einwandfrei! Vielen Dank!
